# Generated by Django 5.1.4 on 2025-02-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='emailaddres',
            new_name='email',
        ),
    ]
